login: &login
  adapter: mysql
  encoding: utf8
  pool: 5
  username: root
  password: password

development:
  <<: *login
  database: demo_app_development

test:
  <<: *login
  database: demo_app_test

production:
  <<: *login
  database: demo_app
